[package]
name = "r_db"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
chrono = { version = "0.4.42", features = ["serde"] }
dotenvy = "0.15"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }